coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 90%
        threshold: 2%
        base: auto

  ignore:
    - "tests/*"
    - "examples/*"
    - "benches/*"
    - "**/*.toml"
    - "**/*.md"
    - "crates/trainer-tests/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
