coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

  ignore:
    - "tests/*"
    - "examples/*"
    - "benches/*"
    - "**/*.toml"
    - "**/*.md"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
