name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for codecov

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang llvm

      - name: Configure CMake with Coverage
        run: |
          cmake -B build -S . \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=Debug \
            -DENABLE_CODE_COVERAGE=ON

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate coverage report
        run: |
          cd build
          llvm-profdata merge -sparse default.profraw -o coverage.profdata
          llvm-cov export -format=lcov -instr-profile=coverage.profdata $(find . -name "*.so" -o -name "*.exe" -o -type f -executable | grep -v "CMakeFiles" | tr '\n' ' ') > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./build/coverage.lcov
          fail_ci_if_error: false
          verbose: true